[build]
  publish = "public"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"